---
name: CI scripts

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-2025"]
        python: >-
          ${{
            (github.event_name == 'pull_request' && fromJSON('["3.10", "3.14"]'))
            || fromJSON('["3.10", "3.11", "3.12", "3.13", "3.14"]')
          }}
        type:
          - brownie
          - buidler
          - dapp
          - embark
          - hardhat
          - solc
          - truffle
          - waffle
          - foundry
          - standard
          - vyper
          - solc_multi_file
          - hardhat_multi_file
          - hardhat_v3
        include:
          # buidler requires older NodeJS
          - type: buidler
            node-version: 12

          - type: hardhat_v3
            node-version: 22
        exclude:
          # Currently broken, tries to pull git:// which is blocked by GH
          - type: embark
          # Requires nix
          - os: windows-2025
            type: dapp
          # Explore foundry support in windows
          - os: windows-2025
            type: foundry
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false
      - name: Set up shell
        if: runner.os == 'Windows'
        run: |
          printf 'C:\\msys64\\mingw64\\bin\n' >> "$GITHUB_PATH"
          printf 'C:\\msys64\\usr\\bin\n' >> "$GITHUB_PATH"
      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: ${{ matrix.node-version || '20' }}
      - name: Set up Python ${{ matrix.python }}
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true
      - name: Install dependencies
        run: |
          uv pip install .
          solc-select use 0.5.7 --always-install
      - name: Set up nix
        if: matrix.type == 'dapp'
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342  # v31.11.0
      - name: Set up cachix
        if: matrix.type == 'dapp'
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71  # v17
        with:
          name: dapp
      - name: Install Foundry
        if: matrix.type == 'foundry'
        uses: foundry-rs/foundry-toolchain@b00af27efadbc7b4ca8b82abbd903b17cc874d2a  # v1
      - name: Run Tests
        env:
          TEST_TYPE: ${{ matrix.type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          bash "scripts/ci_test_${TEST_TYPE}.sh"
