---
name: CI scripts

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-2025"]
        python: >-
          ${{
            (github.event_name == 'pull_request' && fromJSON('["3.10", "3.14"]'))
            || fromJSON('["3.10", "3.11", "3.12", "3.13", "3.14"]')
          }}
        type:
          - brownie
          - buidler
          - dapp
          - embark
          - hardhat
          - solc
          - truffle
          - waffle
          - foundry
          - standard
          - vyper
          - solc_multi_file
          - hardhat_multi_file
          - hardhat_v3
        include:
          # buidler requires older NodeJS
          - type: buidler
            node-version: 12

          - type: hardhat_v3
            node-version: 22
        exclude:
          # Currently broken, tries to pull git:// which is blocked by GH
          - type: embark
          # Requires nix
          - os: windows-2025
            type: dapp
          # Explore foundry support in windows
          - os: windows-2025
            type: foundry
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Set up shell
        if: runner.os == 'Windows'
        run: |
          printf 'C:\\msys64\\mingw64\\bin\n' >> "$GITHUB_PATH"
          printf 'C:\\msys64\\usr\\bin\n' >> "$GITHUB_PATH"
      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version: ${{ matrix.node-version || '20' }}
      - name: Set up Python ${{ matrix.python }}
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true
      - name: Install dependencies
        run: |
          uv pip install .
          solc-select use 0.5.7 --always-install
      - name: Set up nix
        if: matrix.type == 'dapp'
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3  # v31.10.6
      - name: Set up cachix
        if: matrix.type == 'dapp'
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71  # v17
        with:
          name: dapp
      - name: Install Foundry
        if: matrix.type == 'foundry'
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d  # v1
      - name: Run Tests
        env:
          TEST_TYPE: ${{ matrix.type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          bash "scripts/ci_test_${TEST_TYPE}.sh"
