name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ["dapp"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install dependencies
      run: |
        sudo wget -O /usr/bin/solc https://github.com/ethereum/solidity/releases/download/v0.5.7/solc-static-linux
        sudo chmod +x /usr/bin/solc
        pip install .
    - name: Run Tests
      env:
        TEST_TYPE: ${{ matrix.type }}
        GITHUB_ETHERSCAN: ${{ secrets.GITHUB_ETHERSCAN }}
      run: |
        bash scripts/travis_test_${TEST_TYPE}.sh
